### ISSUE TITLE
Turn connexion problem on jitsi-school-installer

### ISSUE THREAD

**Issue by gaelgerard** [emrahcom/emrah-tools#1]
Bonjour,

First of all MERCI BEAUCOUP for this installer.

I'm quite a newbie with server configuration and Had very hard time to try to configure Turn on a self hosted Jitsi instance.

For my testing purpose, I blocked my windows 10 port 10000 (in/out) and tested to connect unsuccessfully on my self hosted Jitsi.

Since this morning when I found your jitsi-school-installer which allowed me to install a new self hosted Jitsi in a breeze with Turn enabled automagically 💯 

So while testing with my own limited computer I can now connect to others with cam and mic allowed to other people. Ok for me.

But... a friend of mine, connected via VPN to her Corporate Network accepted to test and was not able to share video nor voice.

I had already tested it was working for her on public meet.jit.si and it was working correctly.

I looked at the log files from `/var/log` but the only errors I could find for the Time of our failing test where for Nginx (I replaced the domain name to share below the only error line I found).

Can you please tell me what could be the problem and how I could solve it?

I read about the jitsi cluster installation which sound good also and perhaps it could solve my problem with my friend's private network?

Thank you for your help,

Gaël

    2021/02/09 17:52:18 [crit] 47866#47866: *3498 SSL_write() failed while sending response to client, client: 127.0.0.1, server: videoconference.example.fr, request: "GET /libs/rnnoise.wasm HTTP/1.1", host: "videoconference.example.fr", referrer: "https://videoconference.example.fr/presentation-privee-fde"

**Comment by emrahcom** [comment]
* Does your friend use exactly the same link which works for you?
* Can she connect to the room and see the other participants avatars?
* Did she test with chrome?

The cluster installation uses the same logic and cannot help if we don't understand the root cause

**Comment by gaelgerard** [comment]
- She used the same link but with student affiliation while I was teacher
  - She can connect to the room and see avatar (which are not customized yet) but can't see my video thumbnail. 
  - We didn't test with Chrome I guess because from previous test she told me she was using Firefox
Thank you for your answers. I will continue to explore to reproduce the problem.

**Comment by gaelgerard** [comment]
I found this interesting post for troubleshooting WebRTC connections https://blog.addpipe.com/troubleshooting-webrtc-connection-issues/

As I explained in my question, I blocked Ports 10000 on my win10 and could connect to my jitsi-school-install where I cound't on my self installed version. So I think the port restriction works well with your Turn implementation.

Now, the linked post give clues on what could block connections even with Turn and gives solution to go through.


**3 possible reasons this could happen:**



>    The default STUN/TURN ports are blocked

Shall I try to block 5349 port on my win10 to reproduce the issue? Would using standard Ports 443/80 for Turn be the solution? Wouldn't it cause issues?

>    All UDP ports are blocked

Perhaps our problem? Once again is it safe to use TCP instead of UDP as mentionned in the article?

>     The STUN/TURN protocols are blocked

Finally this reason it could happen seems not applicable to our case because we had a test on public meet.jit.si and it was working correctly.

Do you think it's safe to add those Solutions to resolve my connection problem? Additionaly, in which files shall I add the proposed solutions (Ports and UDP)?

Thank you for your help!

**Comment by emrahcom** [comment]
> As I explained in my question, I blocked Ports 10000 on my win10 and could connect to my jitsi-school-install where I cound't on my self installed version. So I think the port restriction works well with your Turn implementation.

Did you test with 3 participants on the same meeting room? The videobridge is not used (so the UDP/10000 port) if there are only 2 participants (P2P mode). You can use 3 browser tabs to simulate 3 participants


> Shall I try to block 5349 port on my win10 to reproduce the issue? Would using standard Ports 443/80 for Turn be the solution? Wouldn't it cause issues?

The clients don't connect to TURN through TCP/5349, they connect through TCP/443. Therefore no need to test this.

> > All UDP ports are blocked

The clients don't use UDP ports when TURN active. Therefore  blocked UDP ports are not a problem. The clients use only TCP/443 in TURN case

> Do you think it's safe to add those Solutions to resolve my connection problem? Additionaly, in which files shall I add the proposed solutions (Ports and UDP)?

I think the first thing to be sure does the server work with 3 participants who are not behind a corporate firewall.  If you can send be a link with valid teacher token, I can make some tests too. You can get my email from https://emrah.com/

**Comment by gaelgerard** [comment]
Thank you very much for those answers. As already mentionned, I'm quite a newbie in all those WebRTC stuff.

I sent you an email with a Teacher access to my WordPress where I display the Jitsi instance.

Let me know if you need further information?

Best regards,
