### ISSUE TITLE
Can we remove memory restriction check

### ISSUE THREAD

**Issue by hkarakose** [emrahcom/emrah-tools#2]
Hey Emrah
Thanks for the Jitsi installation scripts.

Do we really need the memory check? It prevents users to install the software to 4GB memory instances. Someone might want to install and try how Jitsi works. It can even be used by small groups.

I suggest to remove memory restriction.

**Comment by emrahcom** [comment]
The allowed max memory for JVB and Jicofo is 3072m in the default installation. Therefore if there is less than 8 GB (3 GB for JVB + 3 GB for Jicofo + ~2 GB for nginx, prosody, system) then the services will be crashed at some point.

It's needed to decrease `VIDEOBRIDGE_MAX_MEMORY` and `JICOFO_MAX_MEMORY` values to run on 4 GB but not recommended
